name: Generate Linux Executable

on:
  push:
    tags:
      - 'v*' # 仅当标签匹配vX.Y.Z格式时触发
    branches:
      ["main"]

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        pip install pyinstaller

    - name: Build executable
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        pyinstaller --name zeroctagon-interface-amd64 --onefile --clean index.py
        
    - name: Extract Tag Name
      id: extract_tag_name
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
      
    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/') # 确保只有在标签上才创建Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.extract_tag_name.outputs.tag_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      if: startsWith(github.ref, 'refs/tags/') # 确保只有在标签上才上传Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/zeroctagon-interface-amd64
        asset_name: zeroctagon-interface-amd64
        asset_content_type: application/octet-stream
